import { theme, type ThemeConfig } from "antd";
import type { ResolvedTheme } from "@/types";

// Antd derives hover/active shades from these, so they must be real colours.
// Keep them in sync with src/styles/tokens.css. Sizes follow the Supabase
// dashboard: 26px "tiny" and 34px default controls, 6px radius, flat buttons.
const palette = {
  light: {
    background: "#fcfcfc",
    foreground: "#171717",
    foregroundLight: "#525252",
    mutedForeground: "#707070",
    foregroundMuted: "#a0a0a0",
    card: "#ffffff",
    popover: "#ffffff",
    surfaceMuted: "#f8f8f8",
    accent: "#f1f1f1",
    selection: "#ebebeb",
    border: "#e4e4e4",
    borderStrong: "#d2d2d2",
    borderStronger: "#b8b8b8",
    buttonBg: "#ffffff",
    primary: "#188552",
    primaryHover: "#14744a",
    brand: "#24b573",
    destructive: "#dc2626",
    warning: "#b45309",
  },
  dark: {
    background: "#121212",
    foreground: "#ededed",
    foregroundLight: "#b4b4b4",
    mutedForeground: "#8f8f8f",
    foregroundMuted: "#6a6a6a",
    card: "#171717",
    popover: "#1c1c1c",
    surfaceMuted: "#1c1c1c",
    accent: "#232323",
    selection: "#2a2a2a",
    border: "#2e2e2e",
    borderStrong: "#3d3d3d",
    borderStronger: "#4d4d4d",
    buttonBg: "#232323",
    primary: "#005a35",
    primaryHover: "#006b40",
    brand: "#36c281",
    destructive: "#ef4444",
    warning: "#f5a524",
  },
} as const;

export function getAntdTheme(mode: ResolvedTheme): ThemeConfig {
  const c = palette[mode];

  return {
    algorithm: mode === "dark" ? theme.darkAlgorithm : theme.defaultAlgorithm,
    token: {
      fontFamily:
        '"Inter Variable", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
      fontFamilyCode:
        '"Source Code Pro", ui-monospace, "SFMono-Regular", Menlo, monospace',
      fontSize: 14,
      fontSizeSM: 12,
      borderRadius: 6,
      borderRadiusSM: 4,
      borderRadiusXS: 2,
      borderRadiusLG: 6,
      controlHeight: 34,
      controlHeightSM: 26,
      controlHeightLG: 38,
      lineWidthFocus: 2,
      colorPrimary: c.primary,
      colorPrimaryHover: c.primaryHover,
      colorPrimaryActive: c.primaryHover,
      // antd draws every focus-visible outline in this colour.
      colorPrimaryBorder: c.primary,
      colorLink: c.foreground,
      colorSuccess: c.brand,
      colorError: c.destructive,
      colorWarning: c.warning,
      colorInfo: c.foregroundLight,
      colorText: c.foreground,
      colorTextSecondary: c.foregroundLight,
      colorTextTertiary: c.mutedForeground,
      colorTextQuaternary: c.foregroundMuted,
      colorTextPlaceholder: c.foregroundMuted,
      colorTextDescription: c.mutedForeground,
      colorIcon: c.mutedForeground,
      colorIconHover: c.foreground,
      colorBgBase: c.background,
      colorBgLayout: c.background,
      colorBgContainer: c.card,
      colorBgElevated: c.popover,
      colorBgMask: "rgba(0, 0, 0, 0.5)",
      colorBorder: c.borderStrong,
      colorBorderSecondary: c.border,
      colorSplit: c.border,
      colorFill: c.selection,
      colorFillSecondary: c.accent,
      colorFillTertiary: c.accent,
      colorFillQuaternary: c.surfaceMuted,
      controlItemBgHover: c.accent,
      controlItemBgActive: c.selection,
      controlItemBgActiveHover: c.selection,
      colorBgSpotlight: c.popover,
      colorTextLightSolid: "#ffffff",
      boxShadow:
        "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
      boxShadowSecondary:
        "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
      motionDurationFast: "0.1s",
      motionDurationMid: "0.2s",
      motionEaseInOut: "cubic-bezier(0, 0, 0.2, 1)",
    },
    components: {
      Button: {
        fontWeight: 400,
        iconGap: 8,
        contentFontSize: 14,
        contentFontSizeSM: 14,
        paddingInline: 12,
        paddingInlineSM: 10,
        primaryShadow: "none",
        defaultShadow: "none",
        dangerShadow: "none",
        primaryColor: "#ffffff",
        defaultColor: c.foreground,
        defaultBg: c.buttonBg,
        defaultBorderColor: c.borderStrong,
        defaultHoverBg: c.selection,
        defaultHoverColor: c.foreground,
        defaultHoverBorderColor: c.borderStronger,
        defaultActiveBg: c.selection,
        defaultActiveColor: c.foreground,
        defaultActiveBorderColor: c.borderStronger,
        textTextColor: c.foreground,
        textTextHoverColor: c.foreground,
        textTextActiveColor: c.foreground,
        textHoverBg: c.selection,
        borderColorDisabled: c.border,
        defaultBgDisabled: c.surfaceMuted,
      },
      // shadcn input: h-9, border-input, no hover change, focus = ring border
      // + 3px --ring shadow. The resting shadow-xs lives in antd.css.
      Input: {
        controlHeight: 36,
        colorBgContainer: c.surfaceMuted,
        colorBorder: c.borderStrong,
        hoverBorderColor: c.borderStrong,
        activeBorderColor: "var(--ring)",
        activeShadow:
          "0 0 0 3px color-mix(in oklab, var(--ring) 50%, transparent)",
        paddingInline: 12,
        paddingInlineSM: 10,
        inputFontSize: 14,
        inputFontSizeSM: 12,
        colorBgContainerDisabled: c.surfaceMuted,
        colorTextDisabled: c.foreground,
      },
      Segmented: {
        controlHeight: 34,
        // Overriding controlHeight re-derives these (34 × 0.75 ≈ 26), so pin
        // them to the global sizes to line up with small/large buttons and selects.
        controlHeightSM: 26,
        controlHeightLG: 38,
        trackPadding: 3,
        fontSize: 14,
        borderRadius: 6,
        borderRadiusSM: 4,
        trackBg: c.accent,
        itemColor: c.mutedForeground,
        itemHoverColor: c.foreground,
        itemHoverBg: "transparent",
        itemActiveBg: "transparent",
        itemSelectedBg: mode === "dark" ? c.borderStrong : c.card,
        itemSelectedColor: c.foreground,
      },
      Dropdown: {
        fontSize: 12,
        paddingBlock: 6,
        controlPaddingHorizontal: 8,
        controlItemBgHover: c.accent,
        controlItemBgActive: c.selection,
        controlItemBgActiveHover: c.selection,
      },
      Menu: {
        itemSelectedBg: c.selection,
        itemSelectedColor: c.foreground,
      },
      Tooltip: {
        fontSize: 12,
        borderRadius: 6,
        colorTextLightSolid: c.foreground,
        colorBgSpotlight: c.popover,
      },
      Card: {
        colorBorderSecondary: c.border,
        borderRadiusLG: 6,
      },
      Alert: {
        defaultPadding: "10px 14px",
        withDescriptionPadding: "12px 14px",
        withDescriptionIconSize: 16,
      },
      Form: {
        labelColor: c.foregroundLight,
        labelFontSize: 14,
        verticalLabelPadding: "0 0 6px",
        itemMarginBottom: 16,
      },
      Divider: {
        colorSplit: c.border,
      },
      Drawer: {
        colorBgElevated: c.background,
        colorSplit: c.border,
      },
      Notification: {
        width: 356,
        colorBgElevated: c.popover,
      },
      Skeleton: {
        gradientFromColor: c.accent,
        gradientToColor: c.selection,
      },
      Avatar: {
        colorTextPlaceholder: c.foreground,
      },
    },
  };
}
